version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - run:
          name: apt update & upgrade
          command: |
            apt update
            apt upgrade -y
      - run: apt-get install -y python3

      - checkout
      - run:
          name: run tests
          command: python3 test_db2.py
