# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

services:

  db2:
    image: ibmcom/db2
    restart: always
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
    ports:
      - 50000:50000

jobs:
  build:

    runs-on: ubuntu-latest
    env:
     DB2_HOST: localhost
     DB2_DATABASE: testdb
     DB2_USER: db2inst1
     DB2_PASSWORD: password
     DB2_PORT: 50000
     
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and test
      run: |
        python -m pip install pyDes
        python test_db2.py
